# This is a basic workflow to help you get started with Actions

name: gradle-publish-javadoc 


# Controls when the workflow will run
on: 
  # push:
  #  branches: [ "master" ] 
 
  workflow_dispatch: 
    
jobs: 
  create-deploy-javadoc: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: javadoc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with: 
        branch: javadocs
        clean: true
        folder: ./build/docs 
        dry-run: true
